export type Product = {
  id: string;
  image: string;
  title: string;
  rating: number;
  price: string;
  originalPrice?: string;
  discount?: string;
  category: string;
  size: string[];
  isTrending: boolean;
};

export const mockProducts: Product[] = [
  {
    id: "selvedge-denim-jacket",
    image:
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    title: "Selvedge Denim Jacket",
    rating: 4.8,
    price: "$198",
    originalPrice: "$230",
    discount: "15% off",
    category: "Jackets",
    size: ["S", "M", "L"],
    isTrending: true,
  },
  {
    id: "merino-crew-sweater",
    image:
      "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=800&q=80",
    title: "Merino Crew Sweater",
    rating: 4.6,
    price: "$145",
    originalPrice: "$172",
    discount: "16% off",
    category: "Sweaters",
    size: ["S", "M", "L"],
    isTrending: true,
  },
  {
    id: "heritage-oxford-shirt",
    image:
      "https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=800&q=80",
    title: "Heritage Oxford Shirt",
    rating: 4.5,
    price: "$92",
    originalPrice: "$108",
    discount: "15% off",
    category: "Shirts",
    size: ["S", "M", "L"],
    isTrending: false,
  },
  {
    id: "tailored-wool-blazer",
    image:
      "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80",
    title: "Tailored Wool Blazer",
    rating: 4.6,
    price: "$320",
    originalPrice: "$400",
    discount: "20% off",
    category: "Blazers",
    size: ["S", "M", "L"],
    isTrending: true,
  },
  {
    id: "pleated-wool-trousers",
    image:
      "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=800&q=80",
    title: "Pleated Wool Trousers",
    rating: 4.4,
    price: "$210",
    originalPrice: "$248",
    discount: "15% off",
    category: "Pants",
    size: ["S", "M", "L"],
    isTrending: false,
  },
  {
    id: "linen-resort-shirt",
    image:
      "https://images.unsplash.com/photo-1487222477894-8943e31ef7b2?auto=format&fit=crop&w=800&q=80",
    title: "Linen Resort Shirt",
    rating: 4.3,
    price: "$128",
    originalPrice: "$150",
    discount: "15% off",
    category: "Shirts",
    size: ["S", "M", "L"],
    isTrending: false,
  },
  {
    id: "cashmere-shawl-cardigan",
    image:
      "https://images.unsplash.com/photo-1509783236416-c9ad59bae472?auto=format&fit=crop&w=800&q=80",
    title: "Cashmere Shawl Cardigan",
    rating: 4.7,
    price: "$265",
    originalPrice: "$312",
    discount: "15% off",
    category: "Sweaters",
    size: ["S", "M", "L"],
    isTrending: true,
  },
  {
    id: "double-breasted-topcoat",
    image:
      "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80",
    title: "Double-Breasted Topcoat",
    rating: 4.8,
    price: "$580",
    originalPrice: "$640",
    discount: "9% off",
    category: "Coats",
    size: ["S", "M", "L"],
    isTrending: true,
  },
  {
    id: "performance-pique-polo",
    image:
      "https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=800&q=80",
    title: "Performance Piqué Polo",
    rating: 4.2,
    price: "$98",
    originalPrice: "$112",
    discount: "12% off",
    category: "Shirts",
    size: ["S", "M", "L"],
    isTrending: false,
  },
  {
    id: "suede-bomber-jacket",
    image:
      "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80",
    title: "Suede Bomber Jacket",
    rating: 4.7,
    price: "$450",
    originalPrice: "$520",
    discount: "13% off",
    category: "Jackets",
    size: ["S", "M", "L"],
    isTrending: true,
  },
  {
    id: "organic-supima-tee",
    image:
      "https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=800&q=80",
    title: "Organic Supima Tee",
    rating: 4.4,
    price: "$48",
    originalPrice: "$58",
    discount: "17% off",
    category: "T-Shirts",
    size: ["S", "M", "L"],
    isTrending: false,
  },
  {
    id: "seamless-puffer-vest",
    image:
      "https://images.unsplash.com/photo-1487222477894-8943e31ef7b2?auto=format&fit=crop&w=800&q=80",
    title: "Seamless Puffer Vest",
    rating: 4.3,
    price: "$198",
    originalPrice: "$230",
    discount: "14% off",
    category: "Jackets",
    size: ["S", "M", "L"],
    isTrending: false,
  },
  {
    id: "heritage-work-boot",
    image:
      "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80",
    title: "Heritage Work Boot",
    rating: 4.8,
    price: "$285",
    originalPrice: "$330",
    discount: "14% off",
    category: "Shoes",
    size: ["S", "M", "L"],
    isTrending: true,
  },
  {
    id: "minimalist-leather-sneaker",
    image:
      "https://images.unsplash.com/photo-1514986888952-8cd320577b68?auto=format&fit=crop&w=800&q=80",
    title: "Minimalist Leather Sneaker",
    rating: 4.6,
    price: "$215",
    originalPrice: "$248",
    discount: "13% off",
    category: "Shoes",
    size: ["S", "M", "L"],
    isTrending: true,
  },
  {
    id: "recycled-fleece-hoodie",
    image:
      "https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=800&q=80",
    title: "Recycled Fleece Hoodie",
    rating: 4.4,
    price: "$128",
    originalPrice: "$150",
    discount: "15% off",
    category: "Hoodies",
    size: ["S", "M", "L"],
    isTrending: false,
  },
  {
    id: "travel-tech-blazer",
    image:
      "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80",
    title: "Travel Tech Blazer",
    rating: 4.5,
    price: "$360",
    originalPrice: "$410",
    discount: "12% off",
    category: "Blazers",
    size: ["S", "M", "L"],
    isTrending: false,
  },
  {
    id: "japanese-raw-denim",
    image:
      "https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=800&q=80",
    title: "Japanese Raw Denim",
    rating: 4.7,
    price: "$240",
    originalPrice: "$280",
    discount: "14% off",
    category: "Pants",
    size: ["S", "M", "L"],
    isTrending: true,
  },
  {
    id: "ultralight-hiking-shell",
    image:
      "https://images.unsplash.com/photo-1463107971871-fbac9ddb920f?auto=format&fit=crop&w=800&q=80",
    title: "Ultralight Hiking Shell",
    rating: 4.3,
    price: "$210",
    originalPrice: "$248",
    discount: "15% off",
    category: "Jackets",
    size: ["S", "M", "L"],
    isTrending: false,
  },
  {
    id: "quilted-field-jacket",
    image:
      "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80",
    title: "Quilted Field Jacket",
    rating: 4.5,
    price: "$310",
    originalPrice: "$360",
    discount: "14% off",
    category: "Jackets",
    size: ["S", "M", "L"],
    isTrending: false,
  },
  {
    id: "classic-trench-coat",
    image:
      "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80",
    title: "Classic Trench Coat",
    rating: 4.8,
    price: "$540",
    originalPrice: "$600",
    discount: "10% off",
    category: "Coats",
    size: ["S", "M", "L"],
    isTrending: true,
  },
  {
    id: "airweight-running-short",
    image:
      "https://images.unsplash.com/photo-1463107971871-fbac9ddb920f?auto=format&fit=crop&w=800&q=80",
    title: "Airweight Running Short",
    rating: 4.3,
    price: "$68",
    originalPrice: "$82",
    discount: "17% off",
    category: "Shorts",
    size: ["S", "M", "L"],
    isTrending: false,
  },
  {
    id: "refined-knit-polo",
    image:
      "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=800&q=80",
    title: "Refined Knit Polo",
    rating: 4.4,
    price: "$138",
    originalPrice: "$162",
    discount: "15% off",
    category: "Shirts",
    size: ["S", "M", "L"],
    isTrending: false,
  },
  {
    id: "textured-terry-sweatshirt",
    image:
      "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=800&q=80",
    title: "Textured Terry Sweatshirt",
    rating: 4.5,
    price: "$128",
    originalPrice: "$150",
    discount: "15% off",
    category: "Sweatshirts",
    size: ["S", "M", "L"],
    isTrending: false,
  },
  {
    id: "heirloom-leather-belt",
    image:
      "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=800&q=80",
    title: "Heirloom Leather Belt",
    rating: 4.7,
    price: "$98",
    originalPrice: "$118",
    discount: "17% off",
    category: "Accessories",
    size: ["S", "M", "L"],
    isTrending: false,
  },
  {
    id: "artisan-weekender-bag",
    image:
      "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80",
    title: "Artisan Weekender Bag",
    rating: 4.8,
    price: "$420",
    originalPrice: "$480",
    discount: "12% off",
    category: "Bags",
    size: ["S", "M", "L"],
    isTrending: true,
  },
  {
    id: "everyday-crossbody-pack",
    image:
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80",
    title: "Everyday Crossbody Pack",
    rating: 4.4,
    price: "$88",
    originalPrice: "$104",
    discount: "15% off",
    category: "Bags",
    size: ["S", "M", "L"],
    isTrending: false,
  },
  {
    id: "stormproof-parka",
    image:
      "https://images.unsplash.com/photo-1484519332611-516457305ff6?auto=format&fit=crop&w=800&q=80",
    title: "Stormproof Parka",
    rating: 4.8,
    price: "$580",
    originalPrice: "$650",
    discount: "11% off",
    category: "Coats",
    size: ["S", "M", "L"],
    isTrending: true,
  },
  {
    id: "studio-yoga-jogger",
    image:
      "https://images.unsplash.com/photo-1463107971871-fbac9ddb920f?auto=format&fit=crop&w=800&q=80",
    title: "Studio Yoga Jogger",
    rating: 4.2,
    price: "$98",
    originalPrice: "$120",
    discount: "18% off",
    category: "Pants",
    size: ["S", "M", "L"],
    isTrending: false,
  },
  {
    id: "hybrid-commuter-coat",
    image:
      "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80",
    title: "Hybrid Commuter Coat",
    rating: 4.6,
    price: "$420",
    originalPrice: "$470",
    discount: "11% off",
    category: "Coats",
    size: ["S", "M", "L"],
    isTrending: false,
  },
  {
    id: "eco-dyed-cable-knit",
    image:
      "https://images.unsplash.com/photo-1509783236416-c9ad59bae472?auto=format&fit=crop&w=800&q=80",
    title: "Eco-Dyed Cable Knit",
    rating: 4.5,
    price: "$185",
    originalPrice: "$214",
    discount: "14% off",
    category: "Sweaters",
    size: ["S", "M", "L"],
    isTrending: false,
  },
  {
    id: "seaside-camp-shirt",
    image:
      "https://images.unsplash.com/photo-1487222477894-8943e31ef7b2?auto=format&fit=crop&w=800&q=80",
    title: "Seaside Camp Shirt",
    rating: 4.2,
    price: "$115",
    originalPrice: "$135",
    discount: "15% off",
    category: "Shirts",
    size: ["S", "M", "L"],
    isTrending: false,
  },
  {
    id: "technical-biker-jacket",
    image:
      "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80",
    title: "Technical Biker Jacket",
    rating: 4.7,
    price: "$510",
    originalPrice: "$580",
    discount: "12% off",
    category: "Jackets",
    size: ["S", "M", "L"],
    isTrending: true,
  },
  {
    id: "woven-panama-hat",
    image:
      "https://images.unsplash.com/photo-1475180098004-ca77a66827be?auto=format&fit=crop&w=800&q=80",
    title: "Woven Panama Hat",
    rating: 4.3,
    price: "$88",
    originalPrice: "$104",
    discount: "15% off",
    category: "Accessories",
    size: ["S", "M", "L"],
    isTrending: false,
  },
  {
    id: "heritage-satchel-pack",
    image:
      "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80",
    title: "Heritage Satchel Pack",
    rating: 4.6,
    price: "$260",
    originalPrice: "$298",
    discount: "13% off",
    category: "Bags",
    size: ["S", "M", "L"],
    isTrending: false,
  },
];
